---

device: "/dev/sdb"
dev_size: "90g"
vg_name: "harbor"
lv_name: "data"
logical_device: "/dev/harbor/data"
dir_mount:
  - "/harbor"
  - "/harbor/data"
path_mount: "/harbor/data"


# pvcreate /dev/sdb
# vgcreate data /dev/sdb
# lvcreate -n ibm -L 25G data
# mkfs.ext4 /dev/data/ibm
# mkdir /ibm
# mount /dev/data/ibm /ibm/