---
packages:
  to_install:
    - epel-release
    - wget
    - curl
    # - python3
    # - python3-pip
    # - python3-devel
    - python2-pip
    - net-tools
    - bind-utils
    - yum-utils
    - ntp
    - nc

pip:
  to_install:
    - docker
    - cryptography==3.0.0


services:
  to_enabled:
    - ntpd
  to_disabled:
    - firewalld