---
packages:
  to_install:
    - wget
    - curl
    - python3
    - python3-pip
    - python3-devel
    - epel-release
    - net-tools
    - bind-utils
    - yum-utils
    - ntp
    - nc

pip:
  to_install:
    - docker

services:
  to_enabled:
    - ntpd
  to_disabled:
    - firewalld